{{- if .Values.azurekv.servicePrincipal }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: "{{ .Values.azurekv.storeName }}"
spec:
  provider:
    # provider type: azure keyvault
    azurekv:
      # URL of your vault instance
      tenantId: "{{ .Values.azurekv.tenantId }}"
      # azure tenant ID, see: https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-how-to-find-tenant
      vaultUrl: "{{ .Values.azurekv.vaultUrl }}"
      # Reference to the Kubernetes secret containing the service principal credentials
      authSecretRef:
        clientId:
          name: "{{ .Values.azurekv.secretName }}"
          key: ClientID
          namespace: {{ .Release.Namespace }}
        clientSecret:
          name: "{{ .Values.azurekv.secretName }}"
          key: ClientSecret
          namespace: {{ .Release.Namespace }}

{{- end }}