{{- if .Values.azurekv.create }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: "{{ .Values.azurekv.storeName }}"
spec:
  provider:
    # provider type: azure keyvault
    azurekv:
      authType: ManagedIdentity
      # Optionally set the Id of the Managed Identity, if multiple identities are assigned to external-secrets operator
      {{- if .Values.azurekv.identityId -}}
      identityId: "{{ .Values.azurekv.identityId }}"
      {{- end }}
      # URL of your vault instance, see: https://docs.microsoft.com/en-us/azure/key-vault/general/about-keys-secrets-certificates
      vaultUrl: "{{ .Values.azurekv.vaultUrl }}"
{{- end }}
