{{- if .Values.azurekv.create }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: "ext-secrets-ces-all"
spec:
  # The name to be used on the ExternalSecrets
  externalSecretName: "ext-secrets-all"
  refreshTime: "1m"
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
          {{- range .Values.azurekv.namespaces }}
          - {{ . }}
          {{- end }}
  externalSecretSpec:
    refreshInterval: 15m           # rate ESO pulls Azure Key Vault
    secretStoreRef:
      kind: ClusterSecretStore
      name: {{ .Values.azurekv.storeName }}         # name of the SecretStore (or kind specified)
    target:
      name: all-secrets           # name of the k8s Secret to be created
      creationPolicy: Owner
    dataFrom:
    # find all secrets with tags
    - find:
        tags:
          import: "true"
{{- end }}
