{
 "title": "Requests / Limits Recommendations",
 "description": "Recommendations vs. Utilization vs. Requests & Limits",
 "tags": [ "Requests / Limits" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values({namespace=\"$namespace\"},pod)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values({pod=\"$pod\"},container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$container",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "container",
   "targets": [
    {}
   ]
  },
  {
   "title": "$container CPU Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}) by (container)",
     "legendFormat": "CPU usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}) by (container)",
     "legendFormat": "CPU Requests"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}) by (container)",
     "legendFormat": "CPU Limits"
    }
   ]
  },
  {
   "title": "$container CPU Guaranteed QoS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}) by (container))*1.3",
     "legendFormat": "CPU Requests"
    },
    {
     "expr": "(avg(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}) by (container))*1.3",
     "legendFormat": "CPU Limits"
    }
   ]
  },
  {
   "title": "$container CPU Burstable QoS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}) by (container))*0.7",
     "legendFormat": "CPU Requests"
    },
    {
     "expr": "(avg(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}) by (container))*1.35",
     "legendFormat": "CPU Limits"
    }
   ]
  },
  {
   "title": "$container Memory Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(container_memory_working_set_bytes{namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}) by (container)",
     "legendFormat": "Memory usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}) by (container)",
     "legendFormat": "Memory Requests"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{resource=\"memory\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}) by (container)",
     "legendFormat": "Memory Limits"
    }
   ]
  },
  {
   "title": "$container Memory Guaranteed QoS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg(container_memory_working_set_bytes{namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}) by (container))*1.3",
     "legendFormat": "Memory Requests"
    },
    {
     "expr": "(avg(container_memory_working_set_bytes{namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}) by (container))*1.3",
     "legendFormat": "Memory Limits"
    }
   ]
  },
  {
   "title": "$container Memory Burstable QoS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg(container_memory_working_set_bytes{namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}) by (container))*0.7",
     "legendFormat": "Memory Requests"
    },
    {
     "expr": "(avg(container_memory_working_set_bytes{namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}) by (container))*1.35",
     "legendFormat": "Memory Limits"
    }
   ]
  },
  {
   "title": "$container CPU Usage, Requests, Limits vs Recommendations",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}) by (container)",
     "legendFormat": "actual usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}) by (container)",
     "legendFormat": "requests"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}) by (container)",
     "legendFormat": "limits"
    },
    {
     "expr": "(avg(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}) by (container))*1.3",
     "legendFormat": "recommendation target"
    },
    {
     "expr": "(avg(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}) by (container))*0.7",
     "legendFormat": "recommendation lowerbound"
    },
    {
     "expr": "(avg(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}) by (container))*1.35",
     "legendFormat": "recommendation upperbound"
    }
   ]
  },
  {
   "title": "$container Memory Usage, Requests, Limits vs Recommendations",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(container_memory_working_set_bytes{namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}) by (container)",
     "legendFormat": "actual usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}) by (container)",
     "legendFormat": "requests"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{resource=\"memory\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}) by (container)",
     "legendFormat": "limits"
    },
    {
     "expr": "(avg(container_memory_working_set_bytes{namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}) by (container))*1.3",
     "legendFormat": "recommendation target"
    },
    {
     "expr": "(avg(container_memory_working_set_bytes{namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}) by (container))*0.7",
     "legendFormat": "recommendation lowerbound"
    },
    {
     "expr": "(avg(container_memory_working_set_bytes{namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}) by (container))*1.35",
     "legendFormat": "recommendation upperbound"
    }
   ]
  }
 ]
}