apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    app: {{ .Release.Name }}
    component: redis
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: redis
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - name: tcp-redis
              containerPort: 6379
          command:
            - redis-server
            - --maxmemory
            - 48mb
            - --maxmemory-policy
            - allkeys-lru
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 15
            periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    app: {{ .Release.Name }}
    component: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: tcp-redis
      name: tcp-redis
  selector:
    app: {{ .Release.Name }}
    component: redis