apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-ext-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-store
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}-secrets
    creationPolicy: Owner
  data:
    - secretKey: SECRET_KEY
      remoteRef:
        key: prod/ecommerce-api
      property: SECRET_KEY
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: prod/ecommerce-api
        property: POSTGRES_PASSWORD
    - secretKey: STRIPE_SECRET_KEY
      remoteRef:
        key: prod/ecommerce-api
        property: STRIPE_SECRET_KEY
    - secretKey: STRIPE_PUBLISHABLE_KEY
      remoteRef:
        key: prod/ecommerce-api
        property: STRIPE_PUBLISHABLE_KEY
